// <auto-generated />
using System;
using CareMiAPIAuth.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace CareMiAPIAuth.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CareMiAPIAuth.Models.Atendimento", b =>
                {
                    b.Property<int>("cdAtendimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cdAtendimento"));

                    b.Property<string>("dsDescricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("dsHabito")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("dsHereditario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("dsTempoSono")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)");

                    b.Property<DateTime>("dtEnvio")
                        .HasColumnType("DATE");

                    b.Property<int>("fgAtivo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("qtDias")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("cdAtendimento");

                    b.ToTable("T_ATENDIMENTO");
                });

            modelBuilder.Entity("CareMiAPIAuth.Models.Login", b =>
                {
                    b.Property<int>("cdLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cdLogin"));

                    b.Property<string>("dsSenha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<int>("fgAtivo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("nrCpf")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)");

                    b.HasKey("cdLogin");

                    b.ToTable("T_LOGIN");
                });

            modelBuilder.Entity("CareMiAPIAuth.Models.Paciente", b =>
                {
                    b.Property<int>("cdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cdPaciente"));

                    b.Property<string>("flSexoBiologico")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("nmGrupoSanguineo")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("NVARCHAR2(6)");

                    b.Property<string>("nmPaciente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<int>("nrAltura")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("nrPeso")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("cdPaciente");

                    b.ToTable("T_PACIENTE");
                });

            modelBuilder.Entity("CareMiAPIAuth.Models.Usuario", b =>
                {
                    b.Property<int>("cdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cdUsuario"));

                    b.Property<string>("dsEstadoCivil")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("dsNacionalidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("dsProfissao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<DateTime>("dtCadastro")
                        .HasColumnType("DATE");

                    b.Property<DateTime>("dtNascimento")
                        .HasColumnType("DATE");

                    b.Property<int>("fgAtivo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("nmUsuario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("nrCpf")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)");

                    b.Property<string>("nrRg")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)");

                    b.Property<string>("nrTelefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)");

                    b.HasKey("cdUsuario");

                    b.ToTable("T_USUARIO");
                });
#pragma warning restore 612, 618
        }
    }
}
